### ISSUE TITLE
There is no AddLitexEmail Method

### ISSUE THREAD

**Issue by ismkdc** [a-patel/LiteXEmail#5]
Hello i am trying this library to my code but when call services.AddLiteXEmail(); in ConfigureService method ide cannot find this method i am using Litex.Email 9.0.0 at .net 5 on vs for mac

**Comment by a-patel** [comment]
`AddLiteXEmail` is replaced by `AddLiteXSmtpEmail` now.

**Comment by a-patel** [comment]
I have updated the configuration document as well:
[LiteX Smtp Email Configuration](https://github.com/a-patel/LiteXEmail#22--configure-startup-class)
